package com.smide.plugins.springboot;

import com.smide.api.Ide;
import com.smide.api.project.NewProjectTemplate;
import javafx.scene.Node;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.FlowPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;

import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/** A Spring Boot project from start.spring.io, with the usual starters as checkboxes. */
public final class SpringBootTemplate implements NewProjectTemplate {

    private static final Map<String, String> STARTERS = new LinkedHashMap<>();

    static {
        STARTERS.put("web", "Spring Web");
        STARTERS.put("data-jpa", "Spring Data JPA");
        STARTERS.put("validation", "Validation");
        STARTERS.put("actuator", "Actuator");
        STARTERS.put("devtools", "DevTools");
        STARTERS.put("lombok", "Lombok");
        STARTERS.put("security", "Security");
        STARTERS.put("postgresql", "PostgreSQL driver");
        STARTERS.put("h2", "H2 database");
        STARTERS.put("thymeleaf", "Thymeleaf");
        STARTERS.put("data-redis", "Redis");
        STARTERS.put("docker-compose", "Docker Compose support");
    }

    @Override
    public String id() {
        return "java.springboot";
    }

    @Override
    public String displayName() {
        return "Spring Boot";
    }

    @Override
    public String description() {
        return "Generated by start.spring.io with the starters you tick. Needs an internet connection.";
    }

    @Override
    public String iconLiteral() {
        return "mdi2l-leaf";
    }

    @Override
    public Node form(Map<String, String> values) {
        GridPane grid = new GridPane();
        grid.setHgap(8);
        grid.setVgap(6);
        TextField group = new TextField("com.example");
        TextField pkg = new TextField("com.example.demo");
        ComboBox<String> java = new ComboBox<>();
        java.getItems().setAll("21", "17", "24");
        java.setValue("21");
        ComboBox<String> build = new ComboBox<>();
        build.getItems().setAll("maven-project", "gradle-project");
        build.setValue("maven-project");
        values.put("groupId", group.getText());
        values.put("package", pkg.getText());
        values.put("java", java.getValue());
        values.put("type", build.getValue());
        values.put("deps", "web,actuator");
        group.textProperty().addListener((o, a, b) -> values.put("groupId", b));
        pkg.textProperty().addListener((o, a, b) -> values.put("package", b));
        java.valueProperty().addListener((o, a, b) -> values.put("java", b));
        build.valueProperty().addListener((o, a, b) -> values.put("type", b));
        grid.addRow(0, new Label("Group id"), group);
        grid.addRow(1, new Label("Package"), pkg);
        grid.addRow(2, new Label("Java"), java);
        grid.addRow(3, new Label("Build"), build);

        FlowPane deps = new FlowPane(8, 6);
        List<CheckBox> boxes = new ArrayList<>();
        for (Map.Entry<String, String> e : STARTERS.entrySet()) {
            CheckBox cb = new CheckBox(e.getValue());
            cb.setUserData(e.getKey());
            cb.setSelected(e.getKey().equals("web") || e.getKey().equals("actuator"));
            cb.selectedProperty().addListener((o, a, b) -> values.put("deps", selected(boxes)));
            boxes.add(cb);
            deps.getChildren().add(cb);
        }
        Label heading = new Label("STARTERS");
        heading.getStyleClass().add("settings-section");
        return new VBox(8, grid, heading, deps);
    }

    private static String selected(List<CheckBox> boxes) {
        List<String> ids = new ArrayList<>();
        for (CheckBox b : boxes) {
            if (b.isSelected()) {
                ids.add((String) b.getUserData());
            }
        }
        return String.join(",", ids);
    }

    @Override
    public void generate(Ide ide, Path location, String name, Map<String, String> values) throws Exception {
        String artifact = name.replaceAll("[^A-Za-z0-9-]", "-").toLowerCase();
        String url = "https://start.spring.io/starter.zip"
                + "?type=" + enc(values.getOrDefault("type", "maven-project"))
                + "&language=java"
                + "&groupId=" + enc(values.getOrDefault("groupId", "com.example"))
                + "&artifactId=" + enc(artifact)
                + "&name=" + enc(name)
                + "&packageName=" + enc(values.getOrDefault("package", "com.example.demo"))
                + "&javaVersion=" + enc(values.getOrDefault("java", "21"))
                + "&packaging=jar"
                + "&baseDir=" + enc(artifact);
        String deps = values.getOrDefault("deps", "");
        if (!deps.isBlank()) {
            url += "&dependencies=" + enc(deps);
        }
        Path zip = location.resolve("starter.zip");
        ide.downloads().download(url, zip, (m, f) -> ide.statusBar().message(m));
        Path tmp = location.resolve(".starter-tmp");
        ide.downloads().extract(zip, tmp, (m, f) -> {
        });
        Files.deleteIfExists(zip);
        // start.spring.io wraps everything in baseDir; lift its contents into the project folder.
        Path inner = tmp.resolve(artifact);
        Path source = Files.isDirectory(inner) ? inner : tmp;
        try (Stream<Path> entries = Files.list(source)) {
            for (Path entry : entries.toList()) {
                Files.move(entry, location.resolve(entry.getFileName()), StandardCopyOption.REPLACE_EXISTING);
            }
        }
        deleteTree(tmp);
    }

    private static void deleteTree(Path dir) throws IOException {
        if (!Files.exists(dir)) {
            return;
        }
        try (Stream<Path> walk = Files.walk(dir)) {
            for (Path p : walk.sorted(java.util.Comparator.reverseOrder()).toList()) {
                Files.deleteIfExists(p);
            }
        }
    }

    private static String enc(String s) {
        return URLEncoder.encode(s, StandardCharsets.UTF_8);
    }
}
